### ISSUE TITLE
image not showing up in pdf

### ISSUE THREAD

**Issue by rduvoisin** [cakebake/markdown-themeable-pdf#45] opened 2016-05-17 22:12 UTC
I insert an image in md.

`![](serious/roc.png)`   

(No embedded spaces in the filename.)

It doesn't show up in the pdf. (It does show up in "markdown-preview" and It does work with "markdown-pdf" plugin.)

**Comment by cakebake** [comment] 2016-06-26 11:37
duplicate of #41

**Closed as completed by cakebake** 2016-06-26 11:37 UTC

**Comment by IreneCrisologo** [comment] 2016-06-27 11:59
@rduvoisin try `![](./serious/roc.png)` instead
