### ISSUE TITLE
Uncaught Error: Notification must be created with string message: undefined

### ISSUE THREAD

**Issue by shreyateeza** [cakebake/markdown-themeable-pdf#108] opened 2018-07-10 18:28 UTC
After installing markdown-themeable-pdf, on converting to pdf using one of the following ways:
*  Right-click in the editor area when a file is opened and select Markdown to PDF or
*  Right-click on a markdown file in Tree-View and select Markdown to PDF or
*  Press ctrl-shift-E (E = Export) in the editor area when a file is opened

**Atom**: 1.28.1 x64
**Electron**: 2.0.4
**OS**: Ubuntu 18.04
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package 1.2.1

### Stack Trace

Uncaught Error: Notification must be created with string message: undefined

```
At /snap/atom/167/usr/share/atom/resources/app/src/notification.js:21

Error: Notification must be created with string message: undefined
    at Notification.validate (/snap/atom/167/usr/share/atom/resources/app/src/notification.js:21:19)
    at new Notification (/snap/atom/167/usr/share/atom/resources/app/src/notification.js:16:16)
    at NotificationManager.addError (/snap/atom/167/usr/share/atom/resources/app/src/notification-manager.js:154:39)
    at /packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:495:44
    at /packages/markdown-themeable-pdf/node_modules/html-pdf/lib/pdf.js:58:21
    at ChildProcess.respond (/packages/markdown-themeable-pdf/node_modules/html-pdf/lib/pdf.js:126:14)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
  9x -1:11.9.0 core:backspace (input.hidden-input)
     -0:09.9.0 markdown-themeable-pdf:export (div.line)
```

### Non-Core Packages

```
busy-signal 1.4.3 
gpp-compiler 3.0.7 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
markdown-themeable-pdf 1.2.1 
```

**Comment by shreyateeza** [comment] 2018-07-11 15:46
@cakebake Is there a way to fix this issue?
Actually, I didn't get the issue as well. Can you please let me know if this issue is related to the atom or my PC?

**Comment by cakebake** [comment] 2018-09-24 09:57
> Can you please let me know if this issue is related to the atom or my PC?

Hello! Thank´s for your feedback, but I also could not reproduce this issue. Currently I am working on version 2. For version 1, there are no more updates. Closing.

**Closed as completed by cakebake** 2018-09-24 09:57 UTC
