### ISSUE TITLE
Failed to activate the markdown-themeable-pdf package

### ISSUE THREAD

**Issue by steevech** [cakebake/markdown-themeable-pdf#74] opened 2017-03-09 01:43 UTC
[Enter steps to reproduce:]

1. I got the error: "ENOENT: no such file or directory, scandir '/Users/steevechwojko/.atom/packages/markdown-themeable-pdf-1.2.0/node_modules/highlight.js/styles'

2. I manually created this path to see whether it would make a difference. The new error was as shown below. 

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package 1.2.0

### Stack Trace

Failed to activate the markdown-themeable-pdf package

```
At Cannot find module 'ncp'

Error: Cannot find module 'ncp'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.activate (/packages/markdown-themeable-pdf-1.2.0/lib/markdown-themeable-pdf.js:211:33)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:814:28
```

### Commands

```
```

### Non-Core Packages

```
markdown-pdf 1.5.0 
markdown-themeable-pdf 1.2.0 
```

**Comment by cakebake** [comment] 2017-04-09 18:39
Do you still have the problem? Have you reinstalled the package once?

**Comment by ronaldpetty** [comment] 2018-02-21 05:58
When starting Atom 1.25.0-beta1, markdown-themeable-pdf was working at one point.  Now I receive this, have tried reinstalling the module.  I don't know much about the internals of Atom so haven't debugged.  Any thoughts if this is related?

```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1146:7)
    at Object.activate (/Users/ronaldpetty/.atom/packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:212:40)
    at Package.activateNow (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:230:33)
    at measure (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:206:33)
    at Package.measure (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:88:25)
    at activationPromise.Promise (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:200:20)
    at Promise (<anonymous>)
    at Package.activate (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:852:28)
    at PackageManager.activatePackages (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (/Applications/Atom Beta.app/Contents/Resources/app/src/atom-environment.js:867:27)
    at <anonymous>
```

**Comment by ronaldpetty** [comment] 2018-02-21 19:35
I take it thats a no ;)

**Comment by cakebake** [comment] 2018-02-28 09:41
I'm currently doing a rewrite of the entire package. Unfortunately, I could not reproduce your problem. Maybe it will be fixed afterwards for you!

**Comment by dpwrussell** [comment] 2018-02-28 19:08
I can confirm this issue on 1.25.0-beta2, but as you say, rewrite might fix it.

**Comment by RainerEmrich** [comment] 2018-03-16 10:49
Issue confirmed on 1.25.0

**Comment by Morius** [comment] 2018-03-18 08:46
I got the same issues with 1.25.0 with macOS 10.11.6.


```
Path must be a string. Received undefined

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1146:7)
    at Object.activate (/Users/Alex/.atom/packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:212:40)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:230:33)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:206:33)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/src/package.js:200:20)
    at Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:491:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:267:15)
    at bufferStream (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:288:15)
    at Socket.stream.on (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:164:13)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
```

**Comment by miko007** [comment] 2018-03-18 14:33
can confirm on 1.25.0

**Comment by Farenew** [comment] 2018-03-18 15:37
same problem in 1.2.0 with win10.

**Comment by Superdanby** [comment] 2018-03-18 16:34
+1 1.25.0 on Fedora 27.

**Comment by ronaldpetty** [comment] 2018-03-18 19:11
I had to do this manual change in 3 places (markdown-themeable-pdf.js, ..) and then it worked.  The configDirPath is not set for some reason.  I don't know enough on atom at moment to fix properly.

```
        var global = path.join("/Users/ronaldpetty/.atom", relativePath);
        //RON was here - var global = path.join(atom.config.configDirPath, relativePath);
```

In a couple of places.

**Comment by ronaldpetty** [comment] 2018-03-19 02:23
var global = path.join("/Users/ronaldpetty/.atom", relativePath);
        //RON was here - var global = path.join(atom.config.configDirPath, relativePath);

**Comment by idimitrakopoulos** [comment] 2018-03-19 08:52
the above worked for me on Windows

**Comment by cakebake** [comment] 2018-03-19 14:21
Currently I'm doing a complete rewrite. I have already noticed this while programming and corrected there. In the Specs it behaves differently and resolves (Arch Linux) to `/tmp/` on. oO

Any Atom update has probably changed that.

I fix this for the v1 version before the v2 is released... #101

**Closed as completed** 2018-03-19 21:37 UTC
Labels: bug

**Comment by pheraph** [comment] 2018-03-20 10:02
Thanks!

**Comment by outfrost** [comment] 2018-03-24 17:22
Appears fixed in v1.2.1, thank you!

**Comment by cakebake** [comment] 2018-03-25 10:42
No problem ;)

**Comment by Morius** [comment] 2018-03-25 19:54
Thanks a lot.
