### ISSUE TITLE
Uncaught TypeError: htmlToPdf.create(...).toStream is not a function

### ISSUE THREAD

**Issue by SirKitboard** [cakebake/markdown-themeable-pdf#7] opened 2015-09-23 20:34 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.16
**System**: Microsoft Windows 10 Pro
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package, v0.9.1
### Stack Trace

Uncaught TypeError: htmlToPdf.create(...).toStream is not a function

```
At C:\Users\Aditya\.atom\packages\markdown-themeable-pdf\lib\markdown-themeable-pdf.js:433

TypeError: htmlToPdf.create(...).toStream is not a function
  at C:\Users\Aditya\.atom\packages\markdown-themeable-pdf\lib\markdown-themeable-pdf.js:433:20
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

```
### Commands

```
     -0:09.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:07.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:07.1.0 markdown-themeable-pdf:export (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
markdown-pdf, v1.3.9
markdown-preview-plus, v2.1.1
markdown-themeable-pdf, v0.9.1

# Dev
No dev packages
```

**Comment by cakebake** [comment] 2015-09-24 12:16
Can you enter some steps to reproduce?

**Comment by thecodejuicer** [comment] 2015-09-30 21:57
I have also seen this issue on Windows 7 with Atom v 1.0.19 with markdown-themeable-pdf package, v0.9.3.

It was thrown when I right-clicked on the open markdown text and selected "Markdown to PDF". You may want to reopen this issue.

**Comment by cakebake** [comment] 2015-10-01 07:55
Which packages have you installed? Maybe duplicate of #3

**Comment by thecodejuicer** [comment] 2015-10-01 21:43
I believe I have markdown-pdf installed as well. I'll try uninstalling that and see what happens.
If that doesn't fix it I'll do some binary deduction testing on other packages and let you know what I find.

**Comment by cakebake** [comment] 2015-10-02 07:59
Thanks for your help!! I could not reproduce the problem, as I have said so far. :/

**Comment by sander76** [comment] 2015-10-02 09:04
I had the same issue. Disabled markdown-pdf and your plugin works now... Nice !

**Comment by thecodejuicer** [comment] 2015-10-06 15:59
That worked for me as well. Looks like it is just a package conflict.

**Comment by cakebake** [comment] 2015-10-07 08:02
Strange... I will try to catch the errors of required packages better... Maybe this helps users who have those conflicts...

**Comment by ajdfajdfl2003** [comment] 2016-01-13 08:43
Maybe it's because you install this package before you install markdown-pdf.
markdown-pdf and this package are conflicts, so make sure you are removed markdown-pdf.
Then restart Atom.

**Comment by cakebake** [comment] 2016-01-13 09:35
A conflict is of course not desirable. As soon as I can reproduce the behavior, I can do something about! For this reason, the issue remains open :)

**Closed as completed** 2018-02-21 18:52 UTC
