### ISSUE TITLE
Feature Request: generate pdf menu base on markdown title

### ISSUE THREAD

**Issue by ybak** [cakebake/markdown-themeable-pdf#57] opened 2016-09-18 03:22 UTC
Thanks for your great work.
It would be better if the generated pdf includes menu base on markdown title.
like:

```
# h1
## h2
# h1'
## h2'
### h3'
```

 will generate pdf menu:

```
h1
--h2
h1'
--h2'
----h3
```

Thanks.

**Comment by cakebake** [comment] 2017-04-09 19:29
I think - duplicate of #65

**Closed as completed by cakebake** 2017-04-09 19:29 UTC
