### ISSUE TITLE
Uncaught Error: 2015-11-20T11:17:38 [CRITICAL] QWin32PrintEngine::initialize: OpenPrinter failed ...

### ISSUE THREAD

**Issue by nrod** [cakebake/markdown-themeable-pdf#22] opened 2015-11-20 10:22 UTC
[Enter steps to reproduce below:]

**NOTE**: yesterday on `Windows 10` before upgrade to `Windows 10 1511 Build 10586` was working fine.
1. Open an `.md` file.
2. Right-click and select `Markdown to PDF`.
3. And then I get a red floating message with the text below.
4. Thank you in advance for helping.

**Atom Version**: 1.2.3
**System**: Microsoft Windows 10 Pro
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package, v0.10.1
### Stack Trace

Uncaught Error: 2015-11-20T11:17:38 [CRITICAL] QWin32PrintEngine::initialize: OpenPrinter failed (The printer name is invalid.)
2015-11-20T11:17:38 [CRITICAL] QWin32PrintEngine::initialize: OpenPrinter failed (The printer name is invalid.)

```
At C:\Users\Nuno Rodrigues\.atom\packages\markdown-themeable-pdf\lib\markdown-themeable-pdf.js:458

Error: 2015-11-20T11:17:38 [CRITICAL] QWin32PrintEngine::initialize: OpenPrinter failed (The printer name is invalid.)
2015-11-20T11:17:38 [CRITICAL] QWin32PrintEngine::initialize: OpenPrinter failed (The printer name is invalid.)

    at ChildProcess.<anonymous> (C:\Users\Nuno Rodrigues\.atom\packages\markdown-themeable-pdf\node_modules\html-pdf\lib\pdf.js:123:17)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```
### Commands

```
     -2:22.3.0 markdown-preview:toggle (atom-text-editor.editor.is-focused)
     -1:32.2.0 pane:split-left (div.markdown-preview.native-key-bindings)
  3x -0:54.9.0 markdown-preview:toggle (div.markdown-preview.native-key-bindings)
     -0:03.8.0 markdown-themeable-pdf:export (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "markdown-themeable-pdf": {
    "openPdfInAtomWorkspace": false,
    "enableBreaks": true
  }
}
```
### Installed Packages

``` coffee
# User
markdown-preview-opener, v0.1.1
markdown-scroll-sync, v0.4.2
markdown-themeable-pdf, v0.10.1

# Dev
No dev packages
```

**Comment by cakebake** [comment] 2015-11-20 12:50
Duplicate of #15 :) dikamilo wrote:

> This was issue with Windows print service - if print service is disabled, phantomjs will fail.

**Closed as completed by cakebake** 2015-11-20 12:50 UTC
Labels: duplicate

**Comment by nrod** [comment] 2015-11-20 13:00
I am sorry... I didn't check other issues. I came directly here by using the report issue button.
Thanks for the information. It is working now.
And by the way, nice package. The fact that we can change the CSS is just very handy.

**Comment by cakebake** [comment] 2015-11-20 13:03
That's no problem, right now I've still got the overview :) Thanks!!
